spring:
  application:
    name: bbe-msa-bs-customer-management
  r2dbc:
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
logging:
  level:
    org.springframework: WARN